### ISSUE TITLE
Avoid conflating terms

### ISSUE THREAD

**Issue by FerdinandBeaman** [learn-co-curriculum/dsc-more-practice-with-matplotlib-lab#4]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## What should be changed?

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

**Comment by FerdinandBeaman** [comment]
https://learning.flatironschool.com/courses/4344/assignments/121699?module_item_id=253245

The datasets are called "x", "y" and "z". When creating a graph, the program takes in two arguments to be the x and y axis. But the error message refers to the arguments as 'x' and 'y'. So when it said there was a problem with x, it wasn't clear to me that the problem was with the value in the position the program knows as 'x', and I thought it was pointing out a problem with the dataset labeled "x". To avoid this problem, the datasets could just be named "a", b" and "c".

This is similar to a problem I had in the very beginning of the prework, where the word "cities" could refer to multiple things (if I remember correctly, the dictionary we imported was titled "cities", and it had a key in the dictionary also called 'cities'). Certainly, this could be an issue I'd come across in real life when going through someone else's data, but to have this appear at the very beginning when we are not aware of the syntax/vocabulary/etc was a bit confusing.

**Comment by christine-egan42** [comment]
changed to x_values, y_values, z_values for clarity. [39aee81](https://github.com/learn-co-curriculum/dsc-more-practice-with-matplotlib-lab/commit/39aee812fa913ac9a41ff2e5d06c501e79b9f150)
