### ISSUE TITLE
Incorrect Variable Names in Customizing Visualizations with Matplotlib - Lab

### ISSUE THREAD

**Issue by rjlatail** [learn-co-curriculum/dsc-more-practice-with-matplotlib-lab#5]
## Link to Canvas

https://learning.flatironschool.com/courses/7620/assignments/268894?module_item_id=646917

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [x ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
# Run this cell without changes
import numpy as np

# Generate a list of numbers from 0 to 99
x_values = np.arange(0,100)

# Multiply values of x_values with 2 to get y_values
y_values = x*2

# Calculate square of values in for variable z_values
z_values = x**2

# Print x_values, y_values and z_values
print (x_values, y_values, z_values)
```

### Concern

![Screenshot 2024-02-02 115923](https://github.com/learn-co-curriculum/dsc-more-practice-with-matplotlib-lab/assets/120394045/c34d4f6d-12f8-4fa6-a365-d40b3ed4d72f)

The variables in lines 8 and 11 are incorrect.  'x' should be replaced with 'x_values'.

## (Optional) Proposed Solution

# Run this cell without changes
import numpy as np

# Generate a list of numbers from 0 to 99
x_values = np.arange(0,100)

# Multiply values of x_values with 2 to get y_values
y_values = x_values*2

# Calculate square of values in for variable z_values
z_values = x_values**2

# Print x_values, y_values and z_values
print (x_values, y_values, z_values)

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for bringing this to our attention; we'll take a look.

**Comment by bpurdy-ds** [comment]
You are correct. Fixing.
